---
- name: Kernel networking sysctls (throughput & queue headroom)
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: "net.core.rmem_max", value: "16777216" }
    - { name: "net.core.wmem_max", value: "16777216" }
    - { name: "net.core.netdev_max_backlog", value: "25000" }
    - { name: "net.core.somaxconn", value: "16384" }
    - { name: "net.ipv4.tcp_mtu_probing", value: "1" }
  become: true

- name: Enable BBR + fq
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: "net.core.default_qdisc", value: "fq" }
    - { name: "net.ipv4.tcp_congestion_control", value: "bbr" }
