---
- name: Install Docker
  ansible.builtin.import_tasks: common/install-docker.yml
- name: Logs
  ansible.builtin.import_tasks: common/logs.yml

- name: DNS
  ansible.builtin.import_tasks: common/dns.yml

- name: Ensure Python3 and pip are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
    state: present
    executable: /usr/bin/pip3

- name: Install jsondiff for Python
  ansible.builtin.pip:
    name: jsondiff
    state: present
    executable: /usr/bin/pip3
