---
- name: Gather Docker Swarm status
  community.docker.docker_swarm_info:
  register: docker_swarm_status
  changed_when: false

- name: Join Docker Swarm
  community.docker.docker_swarm:
    state: join
    join_token: "{{ swarm_node_info['join_token'] }}"
    remote_addrs:
      - "{{ swarm_node_info['manager_ip'] }}:2377"
  when:
    - not ansible_check_mode
    - swarm_node_info is defined
    - (docker_swarm_status.swarm_facts.LocalNodeState | default('inactive')) != 'active'
