---
db_server:
  python:
    # Base system packages needed for database client modules
    packages:
      - python3
      - python3-pip

  pip:
    # Shared pip packages applied before individual database setups
    common_packages: []
  system:
    # Database service account for cron/backups
    user: "{{ db_user.name }}"

  postgres:
    # PostgreSQL defaults
    version: "{{ postgres_version | default(14) }}"
    packages:
      - "postgresql-{{ db_server.postgres.version }}"
    service: postgresql
    pip_packages:
      - psycopg2-binary
    backup_schedule:
      minute: "0"
      hour: "*"

  mysql:
    # MySQL defaults
    packages:
      - mysql-server
    client_package: mysql-client
    service: mysql
    pip_packages:
      - PyMySQL
    backup_schedule:
      minute: "0"
      hour: "*"
