---
- name: Validate environment for database servers
  import_playbook: common/validate_env.yml
  vars:
    required_env_vars:
      - MYSQL_PASSWORD
      - POSTGRES_PASSWORD

- name: DB Servers
  hosts: db_servers
  remote_user: serveradmin
  become: true
  gather_facts: true
  tasks:
    - name: Db role
      ansible.builtin.include_role:
        name: db_server
        tasks_from: main
