name: Ansible Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_LOCAL_TEMP: .ansible/tmp
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ansible tooling
        run: |
          python -m pip install --upgrade pip
          pip install ansible-dev-tools

      - name: Install required collections
        run: ansible-galaxy collection install -r collections/requirements.yml

      - name: Prepare ansible temp directory
        run: mkdir -p .ansible/tmp

      - name: Run ansible-lint
        run: ansible-lint
